version: 2
jobs:
  build:
    machine:
      enabled: true
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker build . -t zeit/dockerignore:test
      - run: mkdir codecov-reports
      - run: docker run -v ":/shared" ...
      - run: |
          docker run --rm -i \
          -e CI=$CI \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $PWD/codecov-reports:/usr/src/app/codecov-reports \
          zeit/dockerignore:test
      - run: bash <(curl -s https://codecov.io/bash)