version: 2
jobs:
  build:
    machine:
      enabled: true
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      # Get node and yarn
      - run: sudo apt-get update
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get install -y nodejs
      - run: ln -s $(which nodejs) usr/local/bin/node
      - run: sudo apt-get update && sudo apt-get install yarn
      - run: sudo apt-get install -y build-essential
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install
      - run: yarn test-ci