version: 2
jobs:
  build:
    machine:
      enabled: true
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker build . -t zeit/dockerignore:test
      - run: |
          docker run --rm -i \
          -e CI=$CI \
          -e CIRCLECI=$CIRCLECI \
          -e CIRCLE_BRANCH=$CIRCLE_BRANCH \
          -e CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM \
          -e CIRCLE_NODE_INDEX=$CIRCLE_NODE_INDEX \
          -e CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME \
          -e CIRCLE_PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME \
          -e CIRCLE_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL \
          -e CIRCLE_PR_NUMBER=$CIRCLE_PR_NUMBER \
          -e CIRCLE_SHA1=$CIRCLE_SHA1 \
          -e CIRCLE_ARTIFACTS=$CIRCLE_ARTIFACTS \
          -e CIRCLE_TEST_REPORTS=$CIRCLE_TEST_REPORTS \
          -v /var/run/docker.sock:/var/run/docker.sock \
          zeit/dockerignore:test